local MIN_PLAYERS = 2
local CHOOSER_DURATION = 10
local GUESS_DURATION = 15
local INTERMISSION_DURATION = 5
local MAX_GUESSES = 4

local TOKEN_POOL = {}
for i = 1, 10 do
    TOKEN_POOL[i] = tostring(i)
end

local Config = {
    MIN_PLAYERS = MIN_PLAYERS,
    CHOOSER_DURATION = CHOOSER_DURATION,
    GUESS_DURATION = GUESS_DURATION,
    INTERMISSION_DURATION = INTERMISSION_DURATION,
    MAX_GUESSES = MAX_GUESSES,
    TOKEN_POOL = TOKEN_POOL,
}

return Config
